office_field="id:officeId_chosen"
office_drop_down_value="xpath://li[contains(text(), 'office_text_value')]"
name_field="id:name"
active_check_box="id:active"
activation_date_field="id:activationDate"
submitted_on_date_field="id:submittedon"
add_clients_field="id:clientMembers"
add_client_choices="xpath://a[contains(@title,'client_entered')]"
add_button="xpath://button[contains(text(), 'Add')]"
external_id_field="id:externalId"
submit_button="id:save"
cancel_button="id:cancel"
group_center_name="xpath://li[contains(text(), 'created_group_name')]"
create_group_error_msg="xpath://label[contains(text(), \"error_message\")]"
client_details_info="xpath://table/tbody//td[contains(text(), 'client_name')]"
add_client_delete_or_x_button="xpath://input[@placeholder='client_name']/parent::div/following-sibling::div/button"
added_client="xpath://input[@placeholder='client_name']"